### PR TITLE
fix: permission and rename

### LINKED ISSUE #5905: 【deepin_V23_beta3】【严重】【一般】【集成测试】【系统】安装nexttrace包后，显示未找到命令
### SUMMARY | 问题概要

【关联集成】：https://github.com/linuxdeepin/developer-center/issues/5903

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
【镜像地址】：https://cdimage.uniontech.com/community/releases/23-Beta2/deepin-desktop-community-23-Beta2-amd64.iso
【版本信息】：nexttrace：1.2.2.2-0
```

### PRE-REQUIREMENT | 预置条件

_No response_

### STEPS TO REPRODUCE | 复现步骤

添加集成仓库后，使用命令下载包：`sudo apt install nexttrace`
终端中输入命令：`nexttrace`，观察终端中显示

### OBSERVED RESULT | 观察到的结果

终端中显示‘未找到命令’：
未找到包

### EXPECTED RESULT | 期望的结果

终端中nexttrace命令正常使用

### ADDITIONAL INFORMATION | 额外补充

_No response_

### PR DESCRIPTION
**Pull request by YukariChiba**
`/usr/bin/NTrace-core` --> `/usr/bin/nexttrace`
setcap `cap_net_raw,cap_net_admin+eip`
fix: https://github.com/linuxdeepin/developer-center/issues/5905

### CODE REVIEW

**Review by hudeng-go — CHANGES_REQUESTED** [review]
link方式是不是会好一点？

**Comment by YukariChiba** [comment]
> link方式是不是会好一点？

fixed.

**Pull request merged**
